export const POPULAR_TITLES = [
  "The Dark Knight",
  "Inception",
  "Interstellar",
  "The Matrix",
  "Pulp Fiction",
  "The Godfather",
  "The Shawshank Redemption",
  "Fight Club",
  "Forrest Gump",
  "The Empire Strikes Back",
  "Star Wars",
  "The Lord of the Rings: The Fellowship of the Ring",
  "The Lord of the Rings: The Return of the King",
  "The Lord of the Rings: The Two Towers",
  "Goodfellas",
  "The Silence of the Lambs",
  "Se7en",
  "The Usual Suspects",
  "Léon: The Professional",
  "Spirited Away",
  "Parasite",
  "The Prestige",
  "The Departed",
  "Gladiator",
  "Memento",
  "The Lion King",
  "Back to the Future",
  "Whiplash",
  "The Intouchables",
  "The Pianist",
  "The Green Mile",
  "Life Is Beautiful",
  "Saving Private Ryan",
  "The Great Dictator",
  "Modern Times",
  "City Lights",
  "Spider-Man: Across the Spider-Verse",
  "Spider-Man: Into the Spider-Verse",
  "Avengers: Endgame",
  "Avengers: Infinity War",
  "The Avengers",
  "Iron Man",
  "Guardians of the Galaxy",
  "Guardians of the Galaxy Vol. 2",
  "Guardians of the Galaxy Vol. 3",
  "Black Panther",
  "Thor: Ragnarok",
  "Captain America: The Winter Soldier",
  "Captain America: Civil War",
  "Doctor Strange",
  "Logan",
  "Deadpool",
  "Joker",
  "The Batman",
  "The Wolf of Wall Street",
  "Django Unchained",
  "Inglourious Basterds",
  "Once Upon a Time in Hollywood",
  "Kill Bill: Vol. 1",
  "Kill Bill: Vol. 2",
  "No Country for Old Men",
  "There Will Be Blood",
  "Blade Runner 2049",
  "Blade Runner",
  "Mad Max: Fury Road",
  "Arrival",
  "Dune",
  "Dune: Part Two",
  "Everything Everywhere All at Once",
  "The Grand Budapest Hotel",
  "Moonlight",
  "La La Land",
  "Coco",
  "Inside Out",
  "Toy Story",
  "Toy Story 2",
  "Toy Story 3",
  "Toy Story 4",
  "Up",
  "WALL-E",
  "Ratatouille",
  "The Incredibles",
  "Finding Nemo",
  "Monsters, Inc.",
  "Your Name.",
  "Weathering with You",
  "Suzume",
  "Princess Mononoke",
  "My Neighbor Totoro",
  "Howl's Moving Castle",
  "The Boy and the Heron",
  "Breaking Bad",
  "Better Call Saul",
  "The Wire",
  "The Sopranos",
  "Game of Thrones",
  "Succession",
  "The Bear",
  "Beef",
  "Stranger Things",
  "The Last of Us",
  "Chernobyl",
  "Band of Brothers",
  "Sherlock",
  "True Detective",
  "Fargo",
  "Mindhunter",
  "The Crown",
  "The Queen's Gambit",
  "Ted Lasso",
  "The Office",
  "Parks and Recreation",
  "Brooklyn Nine-Nine",
  "Friends",
  "Seinfeld",
  "The Big Bang Theory",
  "Modern Family",
  "Arrested Development",
  "Community",
  "Silicon Valley",
  "Atlanta",
  "Fleabag",
  "Barry",
  "Narcos",
  "Money Heist",
  "Squid Game",
  "Dark",
  "The Boys",
  "Invincible",
  "Arcane",
  "Cyberpunk: Edgerunners",
  "Attack on Titan",
  "Death Note",
  "Fullmetal Alchemist: Brotherhood",
  "Demon Slayer",
  "Jujutsu Kaisen",
  "One Piece",
  "Naruto",
  "Dragon Ball Z",
  "Cowboy Bebop",
  "Neon Genesis Evangelion",
  "Vinland Saga",
  "Blue Eye Samurai",
  "Shogun",
  "Fallout",
  "The Gentlemen",
  "3 Body Problem",
  "Ripley",
  "Baby Reindeer",
  "A Man in Full",
  "The Sympathizer"
];
